export const inputData = [
    {
        type: "number",
        label: "Free",
        name: "one",
        id: "one",
        labelValue: 0,
        inputNo: 1,
    },
    {
        type: "number",
        label: "500",
        name: "two",
        id: "two",
        labelValue: 500,
        inputNo: 2,
    },
    {
        type: "number",
        label: "1000",
        name: "three",
        id: "three",
        labelValue: 1000,
        inputNo: 3,
    },
    {
        type: "number",
        label: "1500",
        name: "four",
        id: "four",
        labelValue: 1500,
        inputNo: 4,
    },
    {
        type: "number",
        label: "2000",
        name: "five",
        id: "five",
        labelValue: 2000,
        inputNo: 5,
    },
    {
        type: "number",
        label: "2500",
        name: "six",
        id: "six",
        labelValue: 2500,
        inputNo: 6,
    },
];